import fs from 'fs';
import path from 'path';
import { logger } from './logger';

export interface MachineConfig {
  id: string;
  type: 'scanner' | 'weighing' | 'dimension' | 'combined';
  protocol: 'TCP' | 'Serial' | 'Modbus';
  throughput_per_hour: number;
}

export interface ServiceScaling {
  service: string;
  instances: number;
  cpu: string;
  memory: string;
  reason: string;
}

export interface SetupPlan {
  total_load_per_hour: number;
  recommended_scaling: Record<string, ServiceScaling>;
  mongodb_pool_size: number;
  flush_time_seconds: number;
}

export class SetupIntelligence {
  private static DEFAULT_LIMITS = {
    instances: 1,
    cpu: '0.5 core',
    memory: '512MB'
  };

  static calculateLoad(machines: MachineConfig[]): SetupPlan {
    const totalLoad = machines.reduce((sum, m) => sum + m.throughput_per_hour, 0);
    const scaling: Record<string, ServiceScaling> = {};

    // Logic for Scaling based on throughput
    // Every 1000 parcels/hour => +1 instance for processing-heavy services
    const baseMultiplier = Math.ceil(totalLoad / 1000);

    scaling['incoming-service'] = {
      service: 'incoming-service',
      instances: baseMultiplier,
      cpu: baseMultiplier > 2 ? '1 core' : '0.5 core',
      memory: baseMultiplier > 2 ? '1GB' : '512MB',
      reason: `Handling ${totalLoad} parcels/hour across ${machines.length} machines.`
    };

    scaling['validation-engine'] = {
      service: 'validation-engine',
      instances: Math.ceil(baseMultiplier * 1.5), // Validation is more CPU intensive
      cpu: '1 core',
      memory: '1GB',
      reason: 'Rule processing and bagging logic requirement.'
    };

    scaling['mapper-service'] = {
      service: 'mapper-service',
      instances: baseMultiplier,
      cpu: '0.5 core',
      memory: '512MB',
      reason: 'Client-specific payload mapping.'
    };

    scaling['dataposting-service'] = {
      service: 'dataposting-service',
      instances: Math.ceil(baseMultiplier / 2) || 1,
      cpu: '0.5 core',
      memory: '512MB',
      reason: 'Outgoing data upload queue management.'
    };

    return {
      total_load_per_hour: totalLoad,
      recommended_scaling: scaling,
      mongodb_pool_size: Math.min(100, 10 * baseMultiplier),
      flush_time_seconds: 300 // Standard implementation requirement
    };
  }

  static async applyScaling(sessionId: string, plan: SetupPlan, workspacePath: string) {
    logger.info(`Applying scaling plan for ${plan.total_load_per_hour} parcels/hour...`, 'APP-SCALE');
    // In a real scenario, this would update docker-compose.yml or k8s manifests
    // For this automation, we will mock the adjustment of environment variables
    const envPath = path.join(workspacePath, 'CSND', '.env');
    const envContent = `
# AUTO-GENERATED BY NIDO AUTOMYRIX
TOTAL_LOAD=${plan.total_load_per_hour}
MONGO_POOL_SIZE=${plan.mongodb_pool_size}
FLUSH_TIME_SECONDS=${plan.flush_time_seconds}
LOG_LEVEL=info
    `;
    // fs.writeFileSync(envPath, envContent); // Uncomment when ready to write to workspace
    return envContent;
  }
}
